spring.data.mongodb.uri=mongodb+srv://lakshyasoni2023_db_user:xhCL8oQ75LzMrStl@cluster0.m9bgjo2.mongodb.net/?appName=Cluster0
spring.data.mongodb.database = practice01db
spring.data.mongodb.auto-index-creation = true
